[unstable]
build-std-features = ["compiler-builtins-mem", "panic_immediate_abort" ]
build-std = ["core", "compiler_builtins"]

[build]
target = "target.json"

[alias]
b = "objcopy --release -- -O binary ./sev-fw.bin"